---
deployment:
  tasks:
    - export BE_DEPLOYPATH=home/chrisbcx/wizardcity.rollfortopic.com/spellbook FE_DEPLOYPATH=home/chrisbcx/wizardcity.rollfortopic.com/crystalball
    - /bin/cp -R spellbook $BE_DEPLOYPATH
    - /bin/cp -R crystalball $FE_DEPLOYPATH
